cpu_limit_slave: 0.5
cpu_limit_master: 0.4
slave_number: 2
master_number: 1

java_opts_master: '-Xms1796m -Xmx1796m'
java_opts_slave: '-Xms2396m -Xmx2396m'
max_log_line: 10000
max_log_timeout: 1440
max_obj_timeot: 240

server_name: slave
server_host: 10.0.2.31
server_port: 8480
server_user: admin
server_passwd: admin

master_name: master
master_host: 10.0.2.31
master_port: 8480
master_user: admin
master_passwd: admin
